module.exports = {
  title: "Xanny's Nostr Blog",
  description:
    "Bitcoin and privacy shit.",
  favicon:
    "https://cdn.2nodez.com/favicon.png",
  logo: "https://cdn.2nodez.com/favicon.png",
  npub: "npub17rlc0emedw5xljztfqrmykjaacsx6ujvdas64zznjadrnhhwlavq4jjtgg",
  themes: [
    "dark",
    "halloween",
    "lofi",
    "black",
    "luxury",
    "dracula",
    "business",
    "acid",
  ],
  customThemes: [
    {
      custom: {
        primary: "#ef7951",
        secondary: "#ea0eb3",
        accent: "#9d66d1",
        neutral: "#1D252B",
        "base-100": "#403B59",
        info: "#A0BEE4",
        success: "#12825D",
        warning: "#C87114",
        error: "#E9445F",
      },
    },
  ],
  relays: [
    "wss://relay.snort.social",
    "wss://nostr-pub.wellorder.net",
    "wss://relay.damus.io",
    "wss://nos.lol",
    "wss://relay.nostrplebs.com",
    "wss://relay.2nodez.com",
    "wss://bitcoinforthe.lol",
    "wss://nostr.uselessshit.co",
    "wss://relay.theorangepillapp.com",
    "wss://nostr.lu.ke",
    "wss://nostr.milou.lol",
    "wss://relay-verified.deschooling.us",
    "wss://nostr.fractalized.ovh",
    // "wss://nostr.nostrelay.org",
    // "wss://relay.nostr.ch",
    // "wss://nostr.bitcoiner.social",
    // "wss://nostr.onsats.org",
    // "wss://nostr-relay.wlvs.space",
    // "wss://nostr.zebedee.cloud",
    "wss://relay.nostr.info",
  ],
};
