module.exports = {
  title: "Xanny's Nostr Blog",
  description:
    "Bitcoin and privacy shit.",
  favicon:
    "https://cdn.2nodez.com/favicon.png",
  logo: "https://cdn.2nodez.com/favicon.png",
  npub: "npub17rlc0emedw5xljztfqrmykjaacsx6ujvdas64zznjadrnhhwlavq4jjtgg",
  themes: [
    "dark",
    "halloween",
    "lofi",
    "black",
    "luxury",
    "dracula",
    "business",
    "acid",
  ],
  customThemes: [
    {
      custom: {
        primary: "#ef7951",
        secondary: "#ea0eb3",
        accent: "#9d66d1",
        neutral: "#1D252B",
        "base-100": "#403B59",
        info: "#A0BEE4",
        success: "#12825D",
        warning: "#C87114",
        error: "#E9445F",
      },
    },
  ],
  relays: [
    "wss://nostr-pub.wellorder.net",
    "wss://nostr.mom",
    "wss://nos.lol",
    "wss://relay.nostr.band",
    "wss://relay.nostr.wirednet.jp",
    "wss://offchain.pub",
    //"wss://nostr.oxtr.dev",
    "wss://relay.f7z.io",
    // "wss://nostr.sethforprivacy.com",
    // "wss://nostr.privoxy.io",
    "wss://relay.nostrplebs.com",
    // "wss://relay.plebstr.com",
    // "wss://nostr.notmyhostna.me",
    // "wss://freespeech.casa",
    // "wss://nostr.shroomslab.net",
    // "wss://nostr.0ne.day",
    // "wss://nostr.kollider.xyz",
    // "wss://nostr.ownscale.org",
    // "wss://nostr.cheeserobot.org",
    // "wss://relay.austrich.net",
    // "wss://relay.nostr.ai",
    // "wss://relay.nostr.bg",
    "wss://relayable.org",
    // "wss://nostr.zerofiat.world",
    // "wss://nostr.sidnlabs.nl",
    // "wss://relay.taxi",
    "wss://relay.2nodez.com",
    "wss://bitcoinforthe.lol",
    "wss://nostr.uselessshit.co",
    //"wss://relay.theorangepillapp.com",
    "wss://nostr.lu.ke",
    "wss://nostr.milou.lol",
    "wss://relay-verified.deschooling.us",
    "wss://nostr.fractalized.ovh",
    // "wss://nostr.nostrelay.org",
    // "wss://relay.nostr.ch",
    // "wss://nostr.bitcoiner.social",
    // "wss://nostr.onsats.org",
    // "wss://nostr-relay.wlvs.space",
    // "wss://nostr.zebedee.cloud",
    // "wss://relay.nostr.info",
    "wss://relay.damus.io",
  ],
};
